# Generated by Django 3.1.1 on 2020-10-13 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='game',
            fields=[
                ('number', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('blue', models.CharField(max_length=20)),
                ('purple', models.CharField(max_length=20)),
                ('time', models.TimeField()),
                ('winner', models.CharField(max_length=20)),
                ('loser', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='game_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name=10)),
                ('nick', models.CharField(max_length=20)),
                ('champion', models.CharField(max_length=20)),
                ('Kill', models.IntegerField(verbose_name=3)),
                ('death', models.IntegerField(verbose_name=3)),
                ('assist', models.IntegerField(verbose_name=3)),
                ('CS', models.IntegerField(verbose_name=4)),
                ('CS_in_teamjungle', models.IntegerField(verbose_name=3)),
                ('CS_in_enemyjungle', models.IntegerField(verbose_name=3)),
                ('gold', models.IntegerField(verbose_name=10)),
                ('vision', models.IntegerField(verbose_name=3)),
                ('ward_place', models.IntegerField(verbose_name=3)),
                ('ward_destroyed', models.IntegerField(verbose_name=3)),
                ('Pinkward_purchase', models.IntegerField(verbose_name=3)),
                ('champion_damage', models.IntegerField(verbose_name=10)),
                ('solo_kill', models.IntegerField(verbose_name=2)),
                ('GD_15', models.IntegerField(verbose_name=10)),
                ('CSD_15', models.IntegerField(verbose_name=10)),
                ('XPD_15', models.IntegerField(verbose_name=10)),
                ('LVLD_15', models.IntegerField(verbose_name=10)),
                ('turet_damage', models.IntegerField(verbose_name=10)),
                ('taken_damage', models.IntegerField(verbose_name=10)),
            ],
        ),
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('league', models.CharField(max_length=20)),
                ('short', models.CharField(max_length=20)),
                ('nation', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('position', models.CharField(max_length=20)),
                ('nation', models.CharField(max_length=20)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LM_1.team')),
            ],
        ),
    ]
