# Generated by Django 3.1.1 on 2020-09-27 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LM_1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='nation',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
